# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Hugo Grotius"
license = "GPL-3.0-or-later"
licenselink = "https://github.com/metbril/hugo-grotius/blob/master/LICENSE"
description = "Hugo Grotius Theme"
homepage = "https://github.com/metbril/hugo-grotius/"
tags = []
features = []
min_version = "0.41"

[author]
  name = "Robert van Bregt"
  homepage = "https://robertvanbregt.nl"
