# Example config file for the Grotius Theme

baseURL = "https://www.example.com"
title = "Hugo Grotius Theme Example"
languageCode = "en-US"
copyright = "GPL-3.0-or-later"
theme = "grotius"
themesDir = "../.."

paginate = 3
pluralizeListTitles = true
MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"

[params]
  description = "An example site, demonstrating the Hugo Grotius theme."
  recent_posts_number = 5
  mainSections = ["article", "note"]     # sections on homepage
  favicon = ""
  images = ["/images/hugo.jpg"]

  # Grotius theme
  localStyles = true

  # inlinecss = false

# grotius: h-card properties
[author]
  name = "Hugo Grotius"
  url = "https://en.wikipedia.org/wiki/Hugo_Grotius"
  email = "hugo.grotius@example.com"
  photo = "/images/hugo.jpg"
  locality = "Delft"
  countryName = "Netherlands"
  note = "Jurist. Writer."

[[params.indieweb.endpoint]]
  rel = "authorization_endpoint"
  url = "https://indieauth.com/auth"
[[params.indieweb.endpoint]]
  rel = "token_endpoint"
  url = "https://tokens.indieauth.com/token"
[[params.indieweb.endpoint]]
  rel = "webmention"
  url = ""
[[params.indieweb.endpoint]]
  rel = "pingback"
  url = ""
[[params.indieweb.endpoint]]
  rel = "micropub"
  url = ""
[[params.indieweb.endpoint]]
  rel = "microsub"
  url = ""

[[params.social]]
  name = "Twitter"
  icon = "fa fa-twitter"
  weight = 1
  url = "https://twitter.com/gohugoio"
  rel = "me"
  color = "#1da1f2"
[[params.social]]
  name = "Github"
  icon = "fa fa-github"
  weight = 11
  url = "https://github.com/gohugoio"
  rel = "me"
[[params.social]]
  name = "E-mail"
  icon = "fa fa-envelope"
  weight = 98
  url = "mailto:info@example.org"
[[params.social]]
  name = "RSS"
  icon = "fa fa-rss"
  weight = 99
  url = "/index.xml"
  rel = "alternate"
  type = "application/rss+xml"